### PR TITLE
separate reference parameters to allow non-genbank file formats

### PR DESCRIPTION
**Pull request by jpalmer37**
Fixes as described in #7

### CODE REVIEW

**Review by j3551ca — CHANGES_REQUESTED** [review]
The code looks great - can you update the readme to reflect the concatenated vs. segmented modes before we merge ?

**Comment by jpalmer37** [comment]
Of course! I'll do that shortly. Thanks Jess!

**Comment by jpalmer37** [comment]
README has been updated 👍

**Comment by j3551ca** [comment]
Thanks, John!

**Pull request merged**
